Draft: HTML/CSSの勉強会資料を追加
jigintern/intern-dev-tutorial pull request #12
Opened 2023-08-09 01:12 UTC by haruyuki-16278

HTML/CSSの勉強会で使用する資料を追加します。

現在セクション2(ページを作ってみよう)まで完成です。

2023-08-09 04:52 UTC, dicenull requested changes
一旦レビュー投げます

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +↑で開いてもらった開発者ツールの一番上のタブで「Elememts」もしくは「要素」と書かれているタブがあるのでそこを開いてください。
```suggestion
1.1で開いてもらった開発者ツールの一番上のタブで「Elememts」もしくは「要素」と書かれているタブを開いてください。
```

セクションをまたいで矢印があると、どこを指しているか分かりにくいかもです。
`があるのでそこを`はなくても良いかと思いました。

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +まずWeb開発で必ず使うツールとしてブラウザの開発者ツールの使い方を説明します。
```suggestion
まずWeb開発で必ず使うツールとしてブラウザの開発者ツールがあります。
```

この文では開発者ツールはWeb開発で使うツールであること、使い方を説明することの２つが書いてあるので区切ったほうが読みやすそうです。

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +ここで開発者ツールの左上にある点線と矢印のアイコンをクリックすると、ページの要素をクリックしてツールで要素の詳細を確認できます。
```suggestion
ここで開発者ツールの左上にある点線と矢印のアイコンをクリックすると要素選択ツールが使えます。このツールはページの要素をクリックして要素の詳細を確認できます。
```

下の文でも要素選択ツールという単語が登場するので、これが要素選択ツールであることを書いたほうが良さそうです。

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +また、ここで適当にスタイルを書き換えることもできます。
```suggestion
1-1-1. でやったように要素選択ツールで適当な要素を選択すると、それに合わせて開発者ツール下部にあるスタイルタブ内の表示も変わります。ここでは各要素に適用されているスタイルを確認することができます。
また、ここで適当にスタイルを書き換えることもできます。
```

冗長な表現を削りました。開発ツール→開発者ツール。セレクタという単語はまだ登場していないので、置き換えるか簡単に説明があったほうが良さそうです。

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +外から順にmargin、border、padding、content(内容)の大きさがそれぞれでわかるため意図しない大きさが設定されている部分などを見つけやすいです。
```suggestion
外から順にmargin、border、padding、content それぞれの大きさがわかります。そのため意図しない大きさが設定されている部分などを見つけやすいです。
```

同様に区切ったほうが分かりやすそうです。

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +ここでChromeで使える便利な拡張機能「VisBug」も紹介します。[こちら](https://chrome.google.com/webstore/detail/visbug/cdockenadnadldjbbgcallicgledbeoc?hl=ja)からインストールできます。
```suggestion
ここでChromeで使える便利な拡張機能「VisBug」を紹介します。[こちら](https://chrome.google.com/webstore/detail/visbug/cdockenadnadldjbbgcallicgledbeoc?hl=ja)からインストールできます。
```

拡張機能の紹介はこれが１つ目なので`を`でも良いかと思います。お好みで。

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +様々な機能がありますが、特に便利なガイドツールとインスペクトツールを紹介しておきます。
```suggestion
様々な機能がありますが、特に便利なガイドツールとインスペクトツールを紹介します。
```

IMO

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +このツールはホバー中の要素の詳細が簡単に見れるツールで、devtoolのComputedタブで見ていた要素の大きさだったり、Styleタブで確認した色周りの設定も一発で見れるのが便利です。
```suggestion
このツールはホバー中の要素の詳細が簡単に見れるツールです。開発者ツールのComputedタブで確認した要素の大きさや、Styleタブで確認した色周りの設定を一発で見れるのが便利です。
```

devtool→開発者ツール? ほか文章構成はIMOです

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +↓の画像のようにエディタとエミュレータが表示された状態に遷移するはずです。
```suggestion
↓の画像のようにエディタとエミュレータが表示された状態に遷移します。
```

断定で良さそうです。

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +ではファイルビューアーにあるファイルをすべて削除して準備完了です。
```suggestion
ファイルビューアーにあるファイルをすべて削除して準備完了です。
```

なくてもよさそう。2.1もではから始まるので被りを避けたい気持ちがあります。

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +ではファイルビューアーにあるファイルをすべて削除して準備完了です。
ファイルビューアとファイルビューアーで表記ゆれしてます。
他の単語に合わせてファイルビューアで表現統一するのが良さそうです。

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +先程の`Hello, World !`の前後を`<h1>`\~`</h1>`で囲んで見てください。これでエミュレータに表示されるテキストが大きくなったはずです。
```suggestion
先程の`Hello, World !`の前後を`<h1>`と`</h1>`で囲んで見てください。これでエミュレータに表示されるテキストが大きくなったはずです。
```

IMO

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +このとき↑のコードの`<h1>`,`</h1>`を **タグ**　*（開始タグ、終了タグ）* といい、タグを含む全体を **要素** といいます。ここで使用している`h1`タグは heading のhをとった見出しを示すタグで、ページで最も重要な見出し要素に使うものです。
```suggestion
<h1>Hello, World !</h1>

このとき↑のコードの`<h1>`,`</h1>`を **タグ**　*（開始タグ、終了タグ）* といい、タグを含む全体を **要素** といいます。ここで使用している`h1`タグは heading のhをとった見出しを示すタグで、ページで最も重要な見出し要素に使うものです。  `h1`の1の意味は 2-3-1. で説明します。
```

h1タグを書いたコードもあると良さそうです。h1のhについて説明したので、1についても補足があると良さそうです。
(```が被って上手く表示されなかったのでサジェストではHTMLをそのまま書いてます。適宜置き換えてください)

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +このように、文字列をタグで囲むことをマークアップといい、マークアップすることでブラウザなんの要素かを解釈でき、内容に合わせた表示をとることができます。
```suggestion
このように、文字列をタグで囲むことをマークアップといい、マークアップすることでブラウザが要素を解釈でき、内容に合わせた表示をとることができます。
```
typoとIMO:表現変更

2023-08-09 04:52 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +(StackBlitzでhtmlファイルに `<!` まで入力すると候補に出てくるスニペットに↑のコードを入れ込んだものです)
```suggestion
ではより実用的なHTMLの記述に移っていきます。まずは↓のコードを`index.html`に入力してみてください。  
(StackBlitzでhtmlファイルに `<!` まで入力すると候補に出てくるスニペットに2-1.のコードを入れ込んだものです)
```

↓のコード、↑のコードが紛らわしく思いました。

2023-08-09 07:26 UTC, dicenull requested changes

2023-08-09 07:26 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +これは`<ul>`要素とその子要素の`<li>`要素で表現できます。サンプルでも自己紹介で登場していますね。
```suggestion
説明文などを書いていると特に、箇条書きで事柄を列挙したいことがあります。
これは`<ul>`要素とその子要素の`<li>`要素で表現できます。2-3-1.の見出し要素の使用のポイントや2-3.のサンプルの自己紹介でも登場していますね。
```

2-3-1と2-3どちらも例なので一文にまとめると良さそうです。

2023-08-09 07:26 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +それに対して、私の好きな順に並んだうどんのリストを表現したいときには`<ol>`要素とその子要素の`<li>`要素で記述できます。
```suggestion
それに対して、私の好きな順に並んだうどんのリストを表現したいときのように、順序が重要なものには`<ol>`要素とその子要素の`<li>`要素で記述できます。
```

一つ前の表現に合わせて、`~のように、`とすると良さそうです。

2023-08-09 07:26 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +このときsrcに指定されているURLをすべて書くパスの指定を *絶対パス指定* 、それに対して↓のようにHTMLファイルから見たファイルの位置を指定する方法を *相対パス指定* と言います。
```suggestion
このように`<img>`タグの`src`属性に表示させたい画像までのパスを渡すことで、画像を取得してページに埋め込んで表示してくれます。
```

絶対パス相対パスの話はなくてもいいかも。あってもいいですがimgの話とは段落を分けたほうが良さそうです。

2023-08-09 07:33 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +webにおけるリンクと呼ばれるものは、正式にはハイパーリンクと言います。このハイパーリンクによって様々な文書が相互にリンクされる要素をクモの巣になぞらえてWebと呼ばれるようになったほど、webにおいて欠かせないものです。
```suggestion
webにおけるリンクと呼ばれるものは、正式にはハイパーリンクと言います。このハイパーリンクによって様々な文書が相互にリンクされる要素をクモの巣になぞらえてwebと呼ばれるようになったほど、webにおいて欠かせないものです。
```

ひとつだけ大文字になっていました。

2023-08-09 07:41 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +このようなレイアウトを聖杯レイアウトと言ったりします。実はこの表示上の大きな塊を表現するためのHTML要素があります。
```suggestion
このようなレイアウトを聖杯レイアウトと言います。この表示上の大きな塊を表現するためのHTML要素があります。
```

断定してよさそうです。

2023-08-09 08:11 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +         4. VisBugを使ってみよう
1-1-1.から1-1-3.までは開発者ツールの話で、1-1-4だけ別ツールの話なのでVisBugは1-2.とするのが良いと思います。

2023-08-10 00:11 UTC, haruyuki-16278 commented on getting-started-with-html-css/DOCS.md
> +このとき↑のコードの`<h1>`,`</h1>`を **タグ**　*（開始タグ、終了タグ）* といい、タグを含む全体を **要素** といいます。ここで使用している`h1`タグは heading のhをとった見出しを示すタグで、ページで最も重要な見出し要素に使うものです。
https://github.com/jigintern/intern-dev-tutorial/pull/12/commits/7b07a884166a69e26a4fe52d0cd606abb36ccb8c で修正しました

2023-08-10 00:30 UTC, haruyuki-16278 commented on getting-started-with-html-css/DOCS.md
> +![追記したページ](imgs/self-introduction.png)
c8390234e03d76772e2eac6ea6e965054908a400 で修正しました

2023-08-10 00:39 UTC, haruyuki-16278 commented on getting-started-with-html-css/DOCS.md
> +- 見出し要素の大きさを入れ替えて使用するべきではありません。
https://github.com/jigintern/intern-dev-tutorial/pull/12/commits/98fc1e1a5617e8926509d032ff0c627da6661145 で追記しました。

2023-08-10 01:31 UTC, haruyuki-16278 commented on getting-started-with-html-css/DOCS.md
> +このときsrcに指定されているURLをすべて書くパスの指定を *絶対パス指定* 、それに対して↓のようにHTMLファイルから見たファイルの位置を指定する方法を *相対パス指定* と言います。
考えましたが絶対/相対パスの話はあるべきだと思ったので別の修正としました。

https://github.com/jigintern/intern-dev-tutorial/pull/12/commits/0d881eb0e950a7c31c45152ec76163194e73b847

2023-08-10 01:37 UTC, haruyuki-16278 commented on getting-started-with-html-css/DOCS.md
> +         4. VisBugを使ってみよう
https://github.com/jigintern/intern-dev-tutorial/pull/12/commits/2483a51bedd2cfe2c920f9e7217a2c230b8335ab 修正しました

2023-08-10 01:45 UTC, haruyuki-16278 commented on getting-started-with-html-css/DOCS.md
> +表示が少しだけ変わったかと思います。これは本来2-1.で示したコードでは表示がうまくいっていないことを示しています。
2-2-1.の内容で疑問がある程度解消されると思うので一旦このまま残したいです。

2023-08-10 06:15 UTC, haruyuki-16278 commented
セクション3(CSS関連)を書き終えたのでレビューお願いしたいです。
@dicenull @Futaba-Kosuke

2023-08-10 08:35 UTC, Futaba-Kosuke reviewed
取り急ぎ3-4までです 👀   

また、指摘箇所以外に、改行が少なめなのが気になりました。  
目線を横に動かすのはきついので、もう少し多めに改行入れてもらえると嬉しいです

2023-08-10 08:35 UTC, Futaba-Kosuke commented on getting-started-with-html-css/DOCS.md
> +そのため、現在web開発では *全称セレクタ*`*` を用いて以下のようにするのが一般的です。
こんな感じでどうでしょう 👀 
```suggestion
例えば、↑の図のように額に入った絵を飾る場合、絵そのものの大きさ（`content-box`）ではなく、額を含めた大きさ（`border-box`）を指定できる方が配置しやすいと考えられます。  
しかし、デフォルトでは`content-box`を指定する設定になっています。  
そのため、現在web開発では *全称セレクタ*`*` を用いて以下のように設定するのが一般的です。
```

2023-08-10 08:35 UTC, Futaba-Kosuke commented on getting-started-with-html-css/DOCS.md
> +この内、開発者が気にしなければならないのはUAスタイルシートとオーサースタイルシート、それとCSSの初期値です。
```suggestion
この内、開発者が気にしなければならないのはUAスタイルシートとオーサースタイルシート、CSSの初期値です。
```
冗長かもです

2023-08-10 08:35 UTC, Futaba-Kosuke commented on getting-started-with-html-css/DOCS.md
> +これに対して、3-2.で説明した`box-sizing`プロパティはCSSの初期値によって`content-box`が指定されています。
```suggestion
また、3-2.で説明した`box-sizing`プロパティはCSSの初期値によって`content-box`が指定されています。  
デフォルトでは`content-box`を指定する設定になっているので、`border-box`を指定し直すことを推奨しました。
```

2023-08-10 08:35 UTC, Futaba-Kosuke commented on getting-started-with-html-css/DOCS.md
> +  UAスタイルシートやCSS初期値を上書きしたいとき、要素ごとに毎回CSSで修正するのは大変です。世の中にはCSSリセットと呼ばれるこれらの値を扱いやすい状態にしてくれるものがあり、おおよその場合はcssファイルとして用意されています。
`CSS`と`css`で表記ゆれしてそうです

2023-08-10 08:35 UTC, Futaba-Kosuke commented on getting-started-with-html-css/DOCS.md
> +  - id名は重複してはいけません
idだけ要素型、クラスと表記が違うのが気になりました

2023-08-10 08:51 UTC, Futaba-Kosuke commented
3-5までLGTMです 🙆‍♂️

2023-08-10 13:29 UTC, dicenull commented
文章読むぢからを使い果たしたので明日見ます。

2023-08-10 14:09 UTC, haruyuki-16278 commented on getting-started-with-html-css/DOCS.md
> +  UAスタイルシートやCSS初期値を上書きしたいとき、要素ごとに毎回CSSで修正するのは大変です。世の中にはCSSリセットと呼ばれるこれらの値を扱いやすい状態にしてくれるものがあり、おおよその場合はcssファイルとして用意されています。
https://github.com/jigintern/intern-dev-tutorial/pull/12/commits/206f2d7906695c981055338d877f26cec3fa734d で修正しました

2023-08-10 14:09 UTC, haruyuki-16278 commented on getting-started-with-html-css/DOCS.md
> +  - id名は重複してはいけません
https://github.com/jigintern/intern-dev-tutorial/pull/12/commits/206f2d7906695c981055338d877f26cec3fa734d で修正しました

2023-08-10 14:15 UTC, haruyuki-16278 commented
@dicenull @Futaba-Kosuke 
一旦書き上げてすでにある指摘は対応済みです。
手隙きでレビューもらえると助かります :bow:

2023-08-11 06:26 UTC, dicenull requested changes
通しで読みました。確認お願いします

2023-08-11 06:26 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +    <script src="main.js" async></script>
```suggestion
    <script src="main.js" defer></script>
```

`defer`属性の意味ではdefer属性を追加した、と書いてあるので合わせたほうがよさそうです。

2023-08-11 06:26 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +webページは閲覧者が著者が書いた情報を一方的に受け取るだけのものではありません。
```suggestion
webページは、閲覧者が著者によって提供された情報を一方的に受け取るだけのものではありません。
```

は、が、がと連続しているので言い換えると良さそうです。

2023-08-11 06:26 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +    <script src="main.js" async></script>
ここから先のコードがすべてasyncなので、ここだけdeferにするよりは説明のほうをasyncにするといいかもです。

2023-08-11 06:26 UTC, dicenull commented on getting-started-with-html-css/DOCS.md
> +最後に説明するのは簡単なCSSでのアニメーション、`transition`プロパティを用いた見た目ものを説明しておきます。
```suggestion
最後に説明するのは簡単なCSSでのアニメーション、`transition`プロパティを用いたアニメーションを説明しておきます。
```

IMO: 表現をそろえたほうがよさそう

2023-08-11 09:19 UTC, Futaba-Kosuke reviewed
とりあえずここだけで 👀

2023-08-12 03:04 UTC, haruyuki-16278 commented on getting-started-with-html-css/DOCS.md
> +    <script src="main.js" async></script>
https://github.com/jigintern/intern-dev-tutorial/pull/12/commits/da079ffea8ffffff934da0d467513444f7e45d2e で修正しました。

2023-08-12 03:28 UTC, haruyuki-16278 commented
@dicenull @Futaba-Kosuke  

もらってる指摘のすべてに対応したので確認をお願いします。  
あと一行が半角100字程度になるように改行を加えたのでそれも確認お願いします。 :bow:

2023-08-12 13:56 UTC, dicenull approved these changes
LGTM!!!

2023-08-12 17:26 UTC, haruyuki-16278 commented
@Futaba-Kosuke 
問題なかったら... approveもらえると............... 🥺

2023-08-13 06:04 UTC, Futaba-Kosuke commented
> @Futaba-Kosuke 問題なかったら... approveもらえると............... 🥺

見てるのでもう少々お待ち下さい！

2023-08-13 06:23 UTC, Futaba-Kosuke approved these changes
問題無さそうです！ LGTMです

imo: gif多そうで通信環境によってはcloneに時間がかかりそうなので、資料をcloneする前提の資料の担当の人とかに月曜相談しようと思います

2023-08-13 06:43 UTC, haruyuki-16278 commented
レビューありがとうございました！マージします！

2023-08-13 06:43 UTC, merged