勉強会資料の作成（サーバとの通信）
jigintern/intern-dev-tutorial pull request #3
Opened 2023-07-07 08:31 UTC by Ryo-7

# 概要
インターンの勉強会のための資料を作成。
サーバとクライアントの通信に関しての資料を作成した。

# 変更内容
ドキュメントを追加
CORSの動作を確認するためのプログラムを追加

# 確認箇所
ドキュメント(/communication-with-server/README.md)に誤字、脱字、文章のねじれなどがないか
ドキュメントに読みづらい点、わかりにくい点がないか
手順通りに実装してみて動かないなど、不備はないか
CORS用のプログラムに不備がないか、おかしな記述がないか

2023-07-12 04:15 UTC, nabe1005 commented
み

2023-07-12 04:18 UTC, nabe1005 commented on communication-with-server/README.md
> +サーバーとクライアントが通信を行うためにはhttpを利用するが、このhttpには様々なメソッドが定義されている。
IMO: HTTPは大文字表記のほうがいいような気がします

2023-07-12 04:25 UTC, nabe1005 commented on communication-with-server/README.md
> +> ### TIPS:冪等とは
IMO: べきとう、振り仮名あっても良さそう

2023-07-12 04:29 UTC, nabe1005 commented on communication-with-server/README.md
> +- ログイン完了後、一番上の`session`の項目を確認。(メソッドがPOSTで、Request URLにはパスワード等が入っていないこと、payloadタブを開くとパスワードが入っていることを確認)
IMO:

この箇条書きだけだと、確認するGETとPOSTについてやや不親切かなと感じました。  
GETは冪等性があってという説明や、個人情報を含んでいればPOSTを使いましょう、というところを説明して確認してもらっているので、その辺が確認できるといいかなと思います。  
GETもありそうならgithub内で確認する方がいいような気がする

2023-07-12 04:43 UTC, nabe1005 commented on communication-with-server/README.md
> +## リクエスト(or レスポンス)ヘッダ
IMO: 中でリクエストヘッダ・レスポンスヘッダそれぞれの説明があるので、「リクエストヘッダとレスポンスヘッダ」などで良さそう ( or とか括弧書きは余計な混乱を生みそうだなという意図です )

2023-07-12 04:45 UTC, nabe1005 commented on communication-with-server/README.md
> +## 実際に見てみる
IMO: 上記の実際に見てみる、のものと同じAPIを確認するようにしたほうが良さそう
上記のGETをこれに合わせるのが良さそうかと思います

2023-07-12 04:53 UTC, nabe1005 commented on communication-with-server/README.md
> +# CORSとは
MUST:

下の方にTIPSとしてオリジンの説明がありますが、CORSの説明の前にオリジンの説明があるべきかなと思います。  
また、[同一オリジンポリシー](https://developer.mozilla.org/ja/docs/Web/Security/Same-origin_policy)というものがあり、原則としてオリジンが完全に一致してないとリクエストが認められない、ということの説明があるべきかなと思います。

2023-07-12 04:58 UTC, nabe1005 commented on communication-with-server/README.md
> +CORSプリフライトを発生させないリクエストを単純リクエストと呼ぶ。
MUST: 
この段階では、プリフライトリクエストに対する説明がないので、この表現だと単純リクエストが伝わらないんじゃないかなと思います。

以下の条件を「すべて」満たしている場合は、単純リクエストになります。といった説明だけでいいのではないかなと思います。

2023-07-12 05:01 UTC, nabe1005 commented on communication-with-server/README.md
> +## プリフライトリクエスト
単純リクエストの条件を満たせなかったものは、メインリクエストの前に、プリフライトリクエストを送信して安全かどうかを確認するものという説明が必要かと思います。

2023-07-12 05:01 UTC, nabe1005 commented on communication-with-server/README.md
> +また、CORSには単純リクエストとプリフライトリクエストの2種類がある。
MUST: 
プリフライトリクエストそのものは本来のリクエストの前に送信するものだと思うので、単純リクエストとの2種類という表現はあんまり正しくないような気がしてます

2023-07-12 05:05 UTC, nabe1005 commented on communication-with-server/README.md
> +1. `deno run server.js`を実行
MUST: 
server.jsをローカルで実行するためには、このリポジトリをcloneして、このディレクトリまで移動してくる必要があるかと思いますが、そこの説明も書いた方がいいと思います。
このセクションの前にDenoの環境構築とかリポジトリのcloneは終わってると思うので、ディレクトリ移動くらいはコマンド書くか、説明文があるかどちらかは必須じゃないかと思います

2023-07-12 05:08 UTC, nabe1005 commented
IMO: 
全体を通して説明が中心になってますが、開発する上でこの話に触れているのは、

- GET/POSTその他いろいろをどう使い分けたらいいのか
- CORSって何？どう対策すればいいの？

というところが大きいと思うので、説明+αでこの変のざっくりとしたまとめは必要かなと思います。

説明してそのまま終わってしまってる内容がすごく多いので、何を覚えなきゃ行けないのか・ひとまず開発するときはどうしたらいいのかというところがしっかり伝わるような構成にはしたいです。

2023-07-12 05:19 UTC, nabe1005 commented
これを参考にしました
https://zenn.dev/riko/articles/cors_deepen_understanding

2023-07-14 02:58 UTC, Ryo-7 commented on communication-with-server/README.md
> +> ### TIPS:冪等とは
冪の字が常用漢字ではなかったので全てひらがなにしました。

2023-07-14 03:00 UTC, Ryo-7 commented on communication-with-server/README.md
> +# CORSとは
TIPSをそのまま上に持っていくと流れがおかしなことになるので、文章の中にオリジンの説明も入れました。
また、同一オリジンポリシーの単語も入れました。
同一オリジンポリシー太字にした方が良さそうですかね？ 🤔

2023-07-14 03:03 UTC, Ryo-7 commented
@nabe1005 
指摘事項修正しました。
コメントしていないものについては、指摘の通りに修正したつもりです。
最後にまとめのセクションを追加して、実際に開発するなら、のような話を追加してみましたがどうでしょうか？(もう少し詳しくした方が良いでしょうか？)

2023-07-18 06:25 UTC, nabe1005 commented on communication-with-server/README.md
> +なお、以下の条件をすべて満たすとプリフライト(後述)を発生させないCORSリクエストとなる。
MUST:
以下の記述も含めて、「プリフライト」という表現は正しいとは言えない気がします。
軽く調べた限りでは出てきませんでした。

「プリフライト要求」だったり、「プリフライトリクエスト」と表現するようにする方がいいかと思います。

2023-07-18 07:50 UTC, Ryo-7 commented on communication-with-server/README.md
> +なお、以下の条件をすべて満たすとプリフライト(後述)を発生させないCORSリクエストとなる。
修正しました！

2023-07-20 05:01 UTC, haruyuki-16278 commented
見ます 👓

2023-07-20 05:17 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +> ### TIPS:ぺき等とは
```suggestion
> ### TIPS:べき等とは
```

2023-07-20 06:02 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +オリジンとは、スキーム(プロトコル)、ホスト(ドメイン)、ポート、この3つによって構成されるものである。
オリジンがURLから読み取れるものであることと、本文中でここにしか登場しないスキーム、ホスト、ポートの説明のためにmdnの↓のような図を使えると良さそうだなと思いました。
> ![](https://developer.mozilla.org/ja/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL/mdn-url-all.png)
> 引用: https://developer.mozilla.org/ja/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL#%E5%9F%BA%E6%9C%AC_url_%E3%81%AE%E8%A7%A3%E5%89%96

2023-07-20 06:10 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +1. `Network`タブを開く
![スクリーンショット 2023-07-20 15 10 09](https://github.com/jigintern/intern-dev-tutorial/assets/24760583/0396f712-fa48-4ab7-bac8-56bc773f282a)
Networkタブの見た目くらいはスクショが貼ってあるほうが親切かもしれません

2023-07-20 06:40 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +> これをべき等である、べき等性があるという。
**HTTPリクエストが**冪等性を 持つ良さ/持たない悪さ も書いてあると良さそうに思います。
（リクエスト結果の返却時に障害があり、再リクエストが発生した場合に冪等性がないリクエストだとリソースが破壊されてしまうなど）

2023-07-20 06:57 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +上記のように様々なメソッドがあるが、基本的に使用されるメソッドは`GET`と`POST`の2つである。
```suggestion
上記のように様々なメソッドがあるが、頻繁に使用されるメソッドは`GET`と`POST`の2つである。
```
↑のほうが当たり障りなさそうです。
個人的には `PUT`、 `DELETE` も軽く触れると良いかもと思いますが任せます。

2023-07-20 07:06 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +なお、このbodyに含めた情報のことをペイロードと言う。
ここでいう「安全」の意味を説明する必要があるように思います。（セキュリティ的な意味でない「安全」が何を指しているのかがわからなさそう）

2023-07-20 07:07 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +クエリパラメータはURLの末尾に付与されるため、他人に見られて困る内容(個人情報等)はGETで送信してはいけない。
URLのうちクエリパラメータがどこにつくのかがわかる画像か説明がある方が良さそうです。

2023-07-20 07:13 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +データをbodyに含めるため、セキュリティ的に安全であるように見えるが、通信を傍受されたときに簡単に内容を読み取ることができるため安全ではない。
> 通信を傍受されたときに
これを言い始めると全部セキュリティ的に安全じゃなくなるので不必要に思います（暗号化されてても時間をかければ複合できてしまうので、暗号化は安全ではなく時間を稼いでくれるだけだという認識
HTTP/HTTPSの違いを冒頭で説明して、HTTPSでの通信を前提として書いたほうが良さそう。

2023-07-20 07:26 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +- GETで情報を送るときは、URLの末尾にクエリパラメータとして付与される
```suggestion
- GETリクエストでは、URLのパスの後方に `?key1=value1&key2=value2` と追加することでサーバーに情報を提供できる
```
などが適当に思います。（アンカーがついて末尾でない場合なども考えられるので

2023-07-25 06:39 UTC, Ryo-7 commented on communication-with-server/README.md
> +データをbodyに含めるため、セキュリティ的に安全であるように見えるが、通信を傍受されたときに簡単に内容を読み取ることができるため安全ではない。
こちら、
POSTは別に暗号化してるわけじゃないから気をつけてね
ってことを伝えたいだけだったので、文章書き換えてみました。

2023-07-25 06:41 UTC, Ryo-7 commented on communication-with-server/README.md
> +オリジンとは、スキーム(プロトコル)、ホスト(ドメイン)、ポート、この3つによって構成されるものである。
この画像見やすくて良いんですが、勝手に他のサイトの画像使うのが良くない気がしたので、URLの説明のセクションを追加しました。

2023-07-25 06:47 UTC, Ryo-7 commented on communication-with-server/README.md
> +1. `Network`タブを開く
確かに入れとく方が親切だなと思いました。
ブラウザによって見た目がだいぶ違うのをどうしようかなと思いましたが、画像増えすぎても邪魔なので、一旦Chromeのものだけ追加しておきました。

2023-07-26 02:28 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +オリジンとは、スキーム(プロトコル)、ホスト(ドメイン)、ポート、この3つによって構成されるものである。
見ました :ok:

2023-07-26 02:28 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +1. `Network`タブを開く
みました :ok:

2023-07-26 02:57 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +> これをべき等である、べき等性があるという。
冪等性
「ラーメンください！ラーメンください！ラーメンください！」
「ラーメン3つお待ち！」
「……」

くらいのユーモアがあっても良い気はしますが、それはそうとして `TIPS:べき等とは` に書いてある内容は誤ってる気がします

2023-07-26 05:15 UTC, Ryo-7 commented
@haruyuki-16278 
指摘事項修正しましたので確認お願いします。
修正の不足や、新たに発生した不備等あれば指摘お願いします。
冒頭に2セクション増えているので、その辺りの確認もお願いします。

2023-07-26 07:37 UTC, Ryo-7 commented on communication-with-server/README.md
> +> これをべき等である、べき等性があるという。
ユーモアですか...難しいですね... 🤔 

そもそもの確認ですが、ラーメンを3回注文したあとに、「で、今何個注文通ってる？」「1つやで」ってなるのが冪等で、「3つやで」ってなるのがべき等ではないって認識ですよね？

2023-08-03 07:07 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +> これをべき等である、べき等性があるという。
> そもそもの確認ですが、ラーメンを3回注文したあとに、「で、今何個注文通ってる？」「1つやで」ってなるのが冪等で、「3つやで」ってなるのがべき等ではないって認識ですよね？

そこはあっています。
(これに限らず)修正もらったので送ってるコメントいったんresolveにして必要なところは再度コメントします :bow:

2023-08-04 00:46 UTC, haruyuki-16278 requested changes
再レビューしたので確認お願いします

2023-08-04 00:46 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +> クライアント側が何度同じ処理を実行しても、サーバ側が1度しか実行していないときと同じ状態になることを指す。
```suggestion
> クライアント側が何度**同じパラメータ**でリクエストしても、サーバ側は1度リクエストを処理したときと**同じ状態**になることを指す。  
```

このときレスポンスが変化するのは冪等性には関係しないこともかけると良さそうです。

2023-08-04 00:46 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +> もちろん、購入ボタンの動作としてどちらが正しいかはその仕様書によるが、少なくとも複数回購入が行えるボタンを、GETなどのべき等性があるとされるメソッドで実装してはいけない。
複数回の購入を意図しない連打の場合は、1回しか購入処理がされないのは問題なく複数回購入処理がされるのは不具合になること。複数回の購入を意図する連打の場合は、1回しか購入処理がされないのは不具合で複数回購入処理がされるのは問題ないこと。
サーバー/クライアントの処理を一連の処理として見たときに、クライアントが意図したより多くの変更がリソースに加わってしまうことが非冪等であるという方がより正確な気がしています。

で、処理全体としての情報処理的なべき等とHTTPメソッドの定義的なべき等が同時に話題に出てるのがすごい混乱する気がするのでそこをなんとかしたい気がします。

2023-08-04 00:46 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +まず、HTTPメソッドは`GET`と`POST`の2種類のみを使う。
これ言い切るのだいぶ宗教的に怖いのでやめたほうがよさそうかも

2023-08-04 00:46 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +HTTPで使用されるメソッドや、ヘッダ、CORSについて紹介したが実装する上で意識することは多くない。
普通にそんなことない気がします。というか意識しなくていいなら説明しないのでこの文は再考してほしいです。

2023-08-04 00:46 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +## まとめ
ここまでの指摘も含めてまとめの内容も再考してほしいです

2023-08-08 09:57 UTC, Ryo-7 commented on communication-with-server/README.md
> +GETメソッドはべき等であるとされ、クライアント側からは安全であるとされる。
こちら、一旦suggestionを適用して、手元でサーバ側の実装の話を追加します。

2023-08-10 00:09 UTC, Ryo-7 commented
@haruyuki-16278 
指摘箇所に修正を入れましたので確認お願いします。:pray:

2023-08-10 02:49 UTC, haruyuki-16278 requested changes
ごめんけどいくつか確認お願いします

2023-08-10 02:49 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +HTTPメソッドとして、べき等ではなく安全でないとされる。
```suggestion
**HTTPメソッドとして**、べき等ではなく安全でないとされる。  
```

2023-08-10 02:49 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +この性質が守られるためには、サーバ側でこれを守るように実装されていなければならない。
```suggestion
```

あとでまとめて書いたほうが良さそうなのでべき等のTipsのあとにサジェストいれました。

2023-08-10 02:49 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +GET同様、べき等で無いなどの性質はサーバの実装によるため、HTTPメソッドの仕様通りでは無い場合もある。
```suggestion
```

GETと同様にまとめたほうがよさそう(べき等のTipsのあとにサジェスト)

2023-08-10 02:49 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +> クライアントからのリクエストが一意に判別できるとき、同一のリクエストが複数回行われても、サーバのリソース(データ)が1度リクエストが行われた時と、同一の状態にがなることをべき等性があるという。
```suggestion
> HTTPメソッドでは、ある一つのリクエストを複数回処理しても、一回リクエストを処理した時と、サーバのリソース(データ)が同一の状態になることをべき等性があるという。 

```

このべき等は社会通念から外れるので HTTPメソッドでは と前置きしたほうが良さそう。

一つのリクエストに対して一回処理か複数回処理かで結果が変わらないことが重要で、リクエストそのものの判別は定義外な気がしたので削ってます。

行われた、だと処理の有無に関わらない感じがするのでちゃんと処理もされたニュアンスが欲しいので文言を調整してます。

2023-08-10 02:49 UTC, haruyuki-16278 commented on communication-with-server/README.md
```suggestion
<details>
  <summary>リクエストにおけるべき等と安全</summary>

  ここではHTTPメソッドにおける定義から、GETやPOSTについてべき等性・安全性を説明した。  
  ただし、GETメソッドやPOSTメソッドを用いた*APIリクエストについてのべき等性・安全性*は、メソッドの定義に依らず、**サーバー/クライアントの実装に依存する**ことに注意したい。
</details>

```

2023-08-10 02:49 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +- GETは人に見られてはいけない情報は扱わない
```suggestion
- GETで人に見られてはいけない情報は扱わない
```

2023-08-10 02:49 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +ただし、どのHTTPメソッドを利用するにしても、サーバ側の実装はそのメソッドの使用を守って実装する必要がある。
```suggestion
ただし、どのHTTPメソッドを利用するにしても、サーバ側の実装は原則そのメソッドの仕様を守って実装する必要がある。  
```

typo

2023-08-10 02:49 UTC, haruyuki-16278 commented on communication-with-server/README.md
> +基本、ブラウザが自動で自動で付与するヘッダのみで問題ない。
```suggestion
HTTP通信のヘッダは基本何もせず、ブラウザが自動で自動で付与するヘッダのみで問題ない。  
```
一行で良さそう

2023-08-10 07:16 UTC, Ryo-7 commented on communication-with-server/README.md
> +> クライアントからのリクエストが一意に判別できるとき、同一のリクエストが複数回行われても、サーバのリソース(データ)が1度リクエストが行われた時と、同一の状態にがなることをべき等性があるという。
細かい説明までありがとうございます。:pray:

2023-08-10 07:56 UTC, Ryo-7 commented
@haruyuki-16278 
サジェストにして頂いてありがとうございます。
全て適用しましたので確認お願いします。

2023-08-10 07:57 UTC, haruyuki-16278 approved these changes
完成で良いと思います。お疲れ様でした！

LGTM

2023-08-14 00:34 UTC, Ryo-7 commented
レビューありがとうございました。
nabeさんからも口頭でLGTMいただいたので、マージします。

2023-08-14 00:34 UTC, merged