WIP: Deno KVの資料を作成
jigintern/intern-dev-tutorial pull request #40
Opened 2024-06-04 07:36 UTC by Futaba-Kosuke

### 概要
WIP

### 変更内容

### 確認箇所

### 備考

2024-06-12 09:34 UTC, Ryo-7 requested changes
全体的に読みやすく、スクショ等も含められており、初見でもわかりやすく構成されていると感じました。

また、演習のセクションが折り畳まれているため、必要な情報がぱっと得られ、後から学んだことを調べるときも使いやすそうでいい感じだとおもいます。

少しでも気になったことは全部書くようにしたので、対応できそうなものは対応してもらえればと思います。 🙏

2024-06-12 09:34 UTC, Ryo-7 commented on deno-kv/docs.md
> ++   // ループしながらDeno KVに問い合わせるので、forループをawaitする
> forループをawaitする
と言われると `await for ()`を意味しそうですが、実際は各要素に対してawaitするのでそこがわかりやすいコメントだと嬉しいです。

2024-06-25 08:40 UTC, Futaba-Kosuke commented on deno-kv/docs.md
> +Deno KVは、Deno Land Inc.から提供されているDeno用NoSQLデータベースです。key-valueデータベースに分類されます。Deno公式から提供されていることもあり、Denoから比較的容易に利用できます。β版なので機能は限定的ですが、個人開発程度であれば、十分な性能を発揮してくれるでしょう。
こちらは後で参照する際に、前セクションを読まずとも1-2を読んだだけでdeno kvについて理解できるように記載したものなので、重複したままで行きたいと思います 🙏

2024-06-25 08:42 UTC, Futaba-Kosuke commented on deno-kv/docs.md
> +<summary>練習: DenoのPlaygroundを作ってみよう</summary>
> <summary>準備: DenoのPlaygroundを作ってみよう</summary>

こんな感じでしょうか 🤔

2024-06-25 08:49 UTC, Futaba-Kosuke commented on deno-kv/docs.md
> +1. 後のために、Deno KVに更にデータを追加しておきます
依存性をなくすのであれば他の練習の記載にデータを追加する処理を書かざるを得ないので、押した場合は講師役によしなにやってもらうで良さそうに思います 🙏   
一旦このままでお願いしたいです

2024-06-25 08:59 UTC, Futaba-Kosuke commented on deno-kv/docs.md
> +7. 以下のような画面が開けばOKです。この画面をProject画面と呼びます
公式ではないので注釈入れておきます 🙇   
資料記載するうえで便宜上つけた名前でした

2024-06-25 09:08 UTC, Futaba-Kosuke commented on deno-kv/docs.md
> +2. ページ右側の「New Playground」をクリックします
[直接話した]  
deno deployが一つもないと発生する  
前の講義でdeno deployするはずなのでOK

2024-06-25 09:08 UTC, Futaba-Kosuke commented
@Ryo-7   
指摘箇所修正しました 🙏   
コミットごとに対応したので、それぞれで確認いただければ見やすいかと思います

2024-07-03 07:54 UTC, Ryo-7 commented on deno-kv/docs.md
> +Deno KVは、Deno Land Inc.から提供されているDeno用NoSQLデータベースです。key-valueデータベースに分類されます。Deno公式から提供されていることもあり、Denoから比較的容易に利用できます。β版なので機能は限定的ですが、個人開発程度であれば、十分な性能を発揮してくれるでしょう。
承知しました。
> 前セクションを読まずとも1-2を読んだだけでdeno kvについて理解できるように記載したものなので

これを実現したいだけなら、L26の方消してもいいかもって思いましたが、別に5回も6回も繰り返されててくどいとかではないのでokです。

2024-07-03 08:13 UTC, Ryo-7 commented on README.md
> +  - [README.md](./mysql/README.md)
対応ありがとうございます。
1年これで運用されてて今更なんですが、コロンが二つあるのなんか違和感がすごいです。
他のところが
`タイトル : ディレクトリ名`
になってる気がするので、
`Deno KVとは：deno-kv`
とかどうですか？

2024-07-03 09:04 UTC, Ryo-7 commented on deno-kv/docs.md
> +2. ページ右側の「New Playground」をクリックします
OK

2024-07-03 09:27 UTC, Ryo-7 commented on deno-kv/docs.md
> +<summary>練習: DenoのPlaygroundを作ってみよう</summary>
summaryのまま行くならそれで良いと思うんですが、そもそもsummaryじゃなくても良さそうだと思った感じです。
この後の演習は全て、deno playgroundをつかうのと、開発でplayground使うために見返してもパッと見つけられないのはあんまり良くないかなと思いました。

2024-07-03 09:32 UTC, Ryo-7 commented on deno-kv/docs.md
> +1. 後のために、Deno KVに更にデータを追加しておきます
了解です。
おそらく資料の読み合わせすると思うので、そのときに必要そうなら共有だけお願いします

2024-07-03 09:43 UTC, Ryo-7 commented on deno-kv/docs.md
> +| `["tasks", "user", 1, 1]` | `{ "title": "課題資料を作成する", "description": "2024年の夏季インターンシップ用の資料を作成する", "deadline": "2024-04-30 23:59:59" }` |
対応ありがとうございます。
使い回しやすくなったのに加えて、データが短くなったのでパッと見も見やすくなってとても良くなったと思います。

2024-07-03 09:49 UTC, Ryo-7 commented on deno-kv/docs.md
> +7. 以下のような画面が開けばOKです。この画面をProject画面と呼びます
注釈がついて間違った覚え方をしなくなったのはとても良さそうです。
実際、統一された呼び名がついていると、トラブルなどが起きたときに共有しやすくなるので良さそうだと思いました。　

2024-07-03 09:52 UTC, Ryo-7 commented on deno-kv/docs.md
> ++   // ループしながらDeno KVに問い合わせるので、forループをawaitする
対応ありがとうございます。
コメントで補足されてわかりやすくなったと思います。

2024-07-03 10:03 UTC, Ryo-7 commented on deno-kv/docs.md
> ++   const key = ["student", 1];
対応ありがとうございます。
簡潔でわかりやすい説明が追加されていてとても良さそうです。

2024-07-03 10:07 UTC, Ryo-7 commented on deno-kv/docs.md
> +```js
対応ありがとうございます。
より情報を拾いやすくなって良さそうです。

2024-07-03 10:10 UTC, Ryo-7 commented on deno-kv/docs.md
> +2. 「Save & Deploy」をクリックして、ログに保存ログが表示されていることを確認する
対応ありがとうございます。
変更箇所を見る限り、コピペで増殖してたっぽいですね。
統一感出ていい感じです

2024-07-03 10:12 UTC, Ryo-7 requested changes
コミットごとにまとめてあったので確認しやすかったです。
解決できてない気がしたものについて、コメントに返信する形で追記したので確認お願いします。 :pray:

2024-07-04 05:23 UTC, Futaba-Kosuke commented on deno-kv/docs.md
> +<summary>練習: DenoのPlaygroundを作ってみよう</summary>
[直接話した]  
PlaygroundのDeno KVの資料の本筋ではないのと、外に展開してしまうと資料が縦に長くなってしまうのでこのままでお願いしたいです 🙏

2024-07-04 08:47 UTC, Futaba-Kosuke commented on README.md
> +  - [README.md](./mysql/README.md)
こちら修正しました 🙏

2024-07-25 01:59 UTC, Ryo-7 commented on deno-kv/docs.md
> +<summary>練習: DenoのPlaygroundを作ってみよう</summary>
承知しました

2024-07-25 04:04 UTC, Futaba-Kosuke commented on README.md
> +  - [README.md](./mysql/README.md)
@Ryo-7   
今度こそ修正しました 🙏

2024-07-26 00:24 UTC, Ryo-7 commented on README.md
> +  - [README.md](./mysql/README.md)
ありがとうございます！

2024-07-26 00:33 UTC, Ryo-7 approved these changes
いい感じだと思います！

LGTM 👍

2024-07-26 07:53 UTC, Futaba-Kosuke commented
@Ryo-7   
レビューありがとうございます！こちらマージします 🙏

2024-07-26 07:53 UTC, merged