Denoチュートリアル資料とサンプルプロジェクトの追加
jigintern/intern-dev-tutorial pull request #6
Opened 2023-07-20 01:30 UTC by rough-github

概要
Denoチュートリアル資料とサンプルプロジェクトを作成

変更内容
ドキュメントを追加
雛形となるプログラムの追加

確認箇所
ドキュメント(README.md)に誤字、脱字、文章のねじれなどがないか
ドキュメントに読みづらい点、わかりにくい点がないか
手順通りに実装してみて動かないなど、不備はないか
雛形用のプログラムに不備がないか、おかしな記述がないか

2023-07-20 01:35 UTC, rough-github commented
ファイルの置き場所をミスっているので修正します

2023-08-07 04:08 UTC, nabe1005 commented
みます

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +`ターミナル`は`windows`なら`powershell`、`mac`なら`zsh`などがありますが、なんでも大丈夫です。
Windows は頭大文字になります

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +では次に`deno run --watch --allow-net --allow-read server.js`を紐どいていきましょう。
IMO: 
紐どいていきましょう、という表現があまりしっくりきませんでした

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +では、`--watch --allow-net --allow-read`は何？ということですが、こちらは`index.js`を実行する際の**オプション指定**になります。一つずつ見ていきましょう。
IMO:
`index.js` とありますが、その前まではserver.js で統一されているかと思うので、合わせた方がいいと思います

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +- `--allow-all, -A`: すべて許可
IMO: 
基本的には、権限は必要なものだけを許可するので、適当に`--allow-all` で指定することがないようにしたほうがいい、という説明があったほうがいいかもしれません

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +`--allow-net  --allow-read`のパーミッションが指定されているので、`ネットワークへのアクセス`と`ファイルの読み込み`が許可されています。後ほど説明しますが`server.js`内では、ブラウザからアクセスされた時に`public`フォルダにあるファイルを読み込んで返す処理を行っているため、その際に必要な`ネットワークへのアクセス`と`ファイルの読み込み`を許可している
IMO: 
許可しているということになります、とありますが、「ファイルを読み込んで返す処理を行う」のに必要なので、ネットワークへのアクセスとファイルの読み込みの権限を許可してあげる必要がある、というニュアンスの表現の方が正確になるかなと思います。

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +これは「`var`は使わないでください」といった警告文です。
IMO: 
簡単な説明でいいので、var なんでダメなの？という補足があるといいように思います

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +この「`ルール`」は`deno.json`内の`lint`の箇所で指定しています。
IMO: 
強調したい日本語を、` ` で囲んでコードにしている部分が点在しますが、コードとしての ` ` 部分と、強調したい部分が混在して、見にくいように感じます。

強調したい日本語の部分は、「」で囲むだけで十分かなと思いますし、他に意図がなければコード化する必要はないように感じました(全体通してです)。

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +こちらのサンプルコードでは[公式の設定そのまま](https://deno.land/manual@v1.35.0/getting_started/configuration_file)を使用しています。
公式の設定そのままを使用しています　→ 公式の設定をそのまま使用しています

のほうがいいかなと思います。

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +`Deno`はコードをcheckする機能(`リント`)をすぐに使用できます。
IMO: 
リント、リンター、check など、英単語とカタカナ表記が混在してる部分が特にこのセクションに多いように感じます。

- Lint, Linter, check など、すべての部分を英語に統一する
- 文章中に出てくる場合は、リント、リンター、チェック等カタカナにする

など、記法としてどうするのかを統一したほうが読みやすくなるかなと思います。

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +中身は「`「1+1は2である」というテストが1つ実行され、OKでした`」となっています。
IMO: 日本語強調

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +のように`失敗したテスト`と`なぜ失敗したか`を報告してくれます。
IMO: 日本語強調

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +Denoには`テスト`を実行する環境も標準で備わっています。
IMO:
テストがどういうもので、開発においてどう使うのか、使うとどういういいことがあるのかについて説明があると親切かなと思います

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +のように`失敗したテスト`と`なぜ失敗したか`を報告してくれます。
失敗したテスト → テストが失敗したこと

が正しいかなと思います

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +## ファイル構造を見てみよう
IMO: 
今まで実行したことについて、後付けで説明という流れになっている部分が多いと思うんですが、基本的には説明が先にあるべきかなと思います。  
説明されたことの確認として、実際にプログラムやコマンドを確認したり、実行したりできるほうが理解してもらいやすくなるかと思います。

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +## ファイル構造を見てみよう
また、大事な内容、覚えてほしい内容が序盤(上のほう)にあるほうが自然でいいのかなと思います。
deno.json や テスト に関する話は必須ではないので、Deno ってなんなの？　だったり、どうやって実行するの？　開発時に覚えておくといいのはどんなことなの？　という部分がもっと明確なほうがわかりやすいと思います。

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +`Deno`で「`ファイルを外部から取り込む`」時は`ESModule`というファイルの読み込みの仕組みを採用しています。
IMO: 日本語強調

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +  - ブラウザからリクエストが来た時に、返すファイル一式が入っています。
IMO: 
publicに返すファイルが入っている、というよりは、publicに入っているファイルをそのまま返せるようにしている、プログラムでそういう実装にしているというニュアンスが伝わった方がいいかと思います

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +これは`http`モジュールをいろんなところで使用している場合に毎度`https`から下記必要がなくなったり、`deno.json`の`import`分をみることで、このプロジェクトで使用されているモジュールを一発で確認することができます。
IMO: 
これは、よく使うライブラリだったりURLだったりを入力ミスを防ぐ意図だったり、単純に入力しやすく・短くすることで、開発するときに嬉しいという意図なのかなと思いますが、「これが使えると何が嬉しいのか、便利なのか」ということが説明としてあるべきだと思います。

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +このリクエストを先ほどの`server.js`で説明した、
IMO:
フロント側で呼んだものが、サーバー側でどう処理されているのかを確認しますよ、という説明がないと何をしているのかいまいち伝わりにくいような気がします

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +の部分でキャッチして`"jig.jpインターンへようこそ！👍"`という文字を返却するという流れになります。
IMO: 
キャッチして、という表現はエラーではないので避けた方がいいように思います。

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +サーバーにリクエストを送って、返って文字を表示する流れが
流れ　→　処理

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +# まとめ (Denoって何？)
IMO: 
この説明は序盤にあるべきで、まとめとしてほしいのは、このセクションではどんなことを勉強したのか、内容の中で特に大事な部分の再確認

fetch API だったり、deno run だったり、deno taskだったりの使い方のおさらいがあるといいのかなと思います。

2023-08-07 04:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +# まとめ (Denoって何？)
この辺は箇条書きで示してあげるほうがわかりやすいかなと思います。

2023-08-08 06:37 UTC, Ryo-7 requested changes
かなり細かく書かれており、Denoを使い始めるのに必要な知識が得られそうな内容でとても良いと思います。

気になった点や、誤字等をコメントしましたので確認お願いします。:pray:

2023-08-08 06:37 UTC, Ryo-7 commented on deno-tutorial/README.md
> +では`fetch`関数を使用しています。
```suggestion
ここでは`fetch`APIを使用しています。
```
とかどうでしょうか？
また、他にも`fetch関数`という言葉があると思いますが、fetch APIかfetch メソッドの方が正しいそうです。

2023-08-08 07:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +「**Deno**」は、`JavaScriptやTypeScript`を実行する環境です。
細かいですが、`JavaScriptやTypeScript`の「や」がコードになっているのが気になりました

2023-08-08 07:45 UTC, nabe1005 commented on deno-tutorial/README.md
> +今回はVScodeで`Deno`を快適に使用できるようにするためにこのような設定をします。
設定をします、とありますが、上記手順で設定は終わっていると思うので、「上記手順でVSCodeでDenoを快適に使用できるようにするための設定を行いました」という表現の方がいいかもです

2023-08-09 11:07 UTC, Ryo-7 requested changes
修正ありがとうございます。

もうあといくつか気になった点が出てきたので確認お願いします。:pray:

2023-08-11 11:00 UTC, Ryo-7 requested changes
いくつかコメントしましたので確認お願いします。
他は大丈夫だと思います。

修正が確認できなかった以前の指摘事項はresolveにしてないので、もし、変更せずに行くのであればそのスレッドに変更しない旨を書いてもらえると助かります。:pray:

2023-08-13 04:03 UTC, rough-github commented on deno-tutorial/README.md
> +おそらくないはずです。
こちら差分が出ないように、`.js`ファイルの中身を
- semiColons: false
- singleQuote: true

の状態に修正しました

2023-08-13 06:04 UTC, Ryo-7 commented on deno-tutorial/README.md
> +おそらくないはずです。
対応ありがとうございます！

2023-08-13 06:06 UTC, Ryo-7 approved these changes
全体通して読みやすく、かつ、分かりやすい内容だと思います。

気になる点も他になく、良さそうです。

LGTMです 👍

2023-08-13 21:53 UTC, rough-github commented
@nabe1005 @Ryo-7 
レビューありがとうございます！
こちらマージします💪

一旦マージして、もし何かあれば都度PR投げます。

2023-08-13 21:54 UTC, merged